name: wherostr_social
description: "Wherostr social"
publish_to: "none"
version: 1.2.3+11

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#121212"
  android_12:
    color: "#ffffff"
    color_dark: "#121212"

flutter_launcher_icons:
  image_path: "assets/icon/halloween/1024.png"
  android: true
  adaptive_icon_background: "assets/icon/halloween/android/ic_launcher_background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/icon/halloween/android/ic_launcher_foreground.png" # only available for Android 8.0 devices and above
  image_path_android: "assets/icon/halloween/android/ic_launcher.png" # only available for Android 13 devices and above
  ios: true
  remove_alpha_ios: true
  windows:
    generate: true
  web:
    generate: true
  macos:
    generate: true
  linux:
    generate: true

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  audioplayers: ^6.1.0
  chewie: ^1.7.5
  dart_nostr:
    git:
      url: https://github.com/mapboss/dart_nostr.git
      ref: v8.2.4
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_localizations:
    sdk: flutter
  get_storage: ^2.1.1
  go_router: ^14.1.3
  intl: any
  provider: ^6.1.2
  video_player: ^2.9.2
  text_parser: ^2.3.0
  any_link_preview: ^3.0.2
  shimmer: ^3.0.0
  timeago: ^3.6.1
  bolt11_decoder: ^1.0.2
  flutter_lazy_indexed_stack: ^0.0.6
  flutter_quill: ^10.7.6
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  http: ^1.2.2
  uuid: ^4.4.2
  dart_geohash: ^2.1.0
  maplibre_gl: ^0.20.0
  file_selector: ^1.0.3
  rename_app: ^1.6.1
  flutter_secure_storage: 9.2.2
  geocoding: ^3.0.0
  convert: ^3.1.1
  transparent_image: ^2.0.1
  fuzzy: ^0.5.1
  flutter_svg_provider: ^1.0.7
  local_auth: ^2.3.0
  geolocator: ^13.0.1
  package_info_plus: ^8.0.2
  change_case: ^2.1.0
  appcheck: ^1.5.2
  easy_image_viewer: ^1.5.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.1
  visibility_detector: ^0.4.0+2
  wakelock_plus: ^1.2.8
  universal_html: ^2.2.4
  flutter_cache_manager: ^3.4.1
  flutter_debouncer: ^2.0.0
  nwc: ^1.0.1
  flutter_native_splash: ^2.4.1
  native_device_orientation: ^2.0.3
  exif: ^3.3.0
  image: ^4.2.0
  mime: ^1.0.6
  video_thumbnail: ^0.5.3
  url_launcher: ^6.3.0
  cryptography: ^2.7.0
  kepler: ^1.0.3
  pointycastle: ^3.9.1
  crypto: ^3.0.5
  dismissible_page: ^1.0.2
  permission_handler: ^11.3.1
  image_gallery_saver: ^2.0.3
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/app/
