allprojects {
    repositories {
        google()
        mavenCentral()
    }
    subprojects {
        afterEvaluate { project ->
            if (project.hasProperty('android')) {
                project.android {
                    if (namespace == null) {
                        namespace project.group
                    }
                }
            }
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}
subprojects {
    // TODO: Remove this when image_gallery_saver is updated to support Flutter 3.24.3
    if (project.name == "image_gallery_saver") {
        afterEvaluate {
            android {
                compileSdkVersion 34
            }
        }
    }

    // TODO: Remove this when isar_flutter_libs is updated to support Flutter 3.24.3
    if (project.name == "isar_flutter_libs") {
        afterEvaluate {
            android {
                compileSdkVersion 34
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
